### ISSUE TITLE
Schematic and PCB design

### ISSUE THREAD

**Issue by ksstms** [legokor/TanfolyamRobot#1]
**Required:**
 * STM32F103 TQFP64
 * [DRV8833](https://www.openimpulse.com/blog/products-page/product-category/drv8833-motor-driver-module/) motor driver module
 * [FIT0450](https://wiki.dfrobot.com/Micro_DC_Motor_with_Encoder-SJ01_SKU__FIT0450) encoder motor
 * 3-pin servo output
 * Generic ultrasonic distance sensor ([HC-SR04](https://cdn.sparkfun.com/datasheets/Sensors/Proximity/HCSR04.pdf) or similar) 
 * [TCS3200](https://components101.com/tcs3200-color-sensor-module) color sensor module
 * Character LCD
 * General purpose button
 * Reset button
 * Programming via USB / virtual COM port
 * Programming via SWD
 * Powered by two 18650 cells

**Nice to have:**
 * ESP for remote control

**TODO:**
 - [x] **fix silkscreen**
 - [x] component values
 - [x] add 100n cap to `NRST`, ~~and remove external pull-up~~ as recommended by the datasheet
 - [x] change `5V_USB` reset circuit to have the cap on the fet's gate rather than it's drain
 - [x] change solder jumpers on the FTDI's `RST` side to be able to populate with ~~0805~~ 0603 caps if needed
 - [x] ~~add resistor to `OSC_OUT` (refer to AN2867)~~ use SMD resonator instead
 - [x] change USB transient suppressor diode to ~~SR05~~ USBLC6-2SC6 or similar
 - [x] ~~color sensor power and logic levels should be 5V~~ it should also work with 3.3V
 - [x] change US trigger to 5V
 - [x] add battery polarity protection
 - [x] detect USB connection by STM GPIO
 - [x] remove `MOTOR_FAULTN` pullup
 - [x] add battery voltage measurement

**Comment by ksstms** [comment]
`ENC2_A` and `ENC2_B` are connected to TIM1_CH1N and TIM1_CH2N, which can't be used as the timer's inputs. 
The least complicated solution seems to be moving `ENC2_A/B` to PA6/7 (TIM3_CH1/2) and `MOTOR1/2_IN1` to PB13/14 (TIM1_CH1/2N).
